Kubernetes 3
Otus-DevOps-2017-11/epanoff_microservices pull request #14
Opened 2018-04-08 19:27 UTC by epanoff

* Настроил публикацию ui через NodePort 
* Настроил публикацию ui через LoadBalancer
* Создал ui-ingress.yml
* Настроил шифрование tls
* Задание со * Описал создаваемый объект Secret в виде Kubernetes- манифеста - docker/kubernates/Kube/secret-ui-ingress.yml 
* Настроил mongo-network-policy.yml 
* Настроил динамический Persistance Volume для MongoDb

2018-05-03 04:54 UTC, vitkhab requested changes
В целом, хорошо. У меня получилось заставить приложение работать.
Классно, что описал секрет в виде yaml-конфигурации.

Для зачета нужно исправить:
- `storageClassName` в mongo-claim-dynamic.yml
- сетевую политику mongo-network-policy.yml

Я понимаю, что прошло много времени после сдачи ДЗ. Возможно будет сложно что-то вспомнить. Я готов тебе помочь, если будут вопросы - задавай

2018-05-03 04:54 UTC, vitkhab commented on docker/kubernates/Kube/comment-deployment.yml
> +      - image: epanoff/comment:1.0
Было бы хорошо, если бы данный образ еще был бы и публично доступным.

2018-05-03 04:54 UTC, vitkhab commented on docker/kubernates/Kube/mongo-claim-dynamic.yml
> +  storageClassName: slow
В конфигурации не описан storageClassName с именем "slow". MongoDB будет ожидать создания диска и никогда его не дождется. Зато в конфигурации описан другой класс, можно указать его.

В гисте была опечатка в этом месте. Тем не менее на слайдах презинтации - все указано правильно.

2018-05-03 04:54 UTC, vitkhab commented on docker/kubernates/Kube/mongo-network-policy.yml
> +          componetn: post
Неправильно применение правил сетевой политики.
Все правила описанные в `podSelector` должны выполниться, чтобы правило сработало, между условиями `podSelector` ставится операция логического _И_. То есть трафик разрешен только для подов со всеми Label'ами app=reddit, component=comment и component=post. В конфигурации таких подов нет.

Правила в рамках `from` отрабатываются до первого совпадения (работают так, если бы между ними стояла операция логического ИЛИ). То есть можно описать несколько `podSelector`

2018-05-30 13:36 UTC, epanoff commented on docker/kubernates/Kube/mongo-claim-dynamic.yml
> +  storageClassName: slow
Поправил.

2018-05-30 13:36 UTC, epanoff commented on docker/kubernates/Kube/mongo-network-policy.yml
> +          componetn: post
Поправил.

2018-06-08 18:08 UTC, vitkhab approved these changes
Спасибо за сделанные исправления!

Можно мерджить.

2018-06-09 08:45 UTC, merged